global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: ['eth2:5054']
  - job_name: 'validator'
    static_configs:
      - targets: ['validator:5064']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'geth'
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
    - targets:
      - eth1:6060 
